### ISSUE TITLE
Running multiple yarrp instances

### ISSUE THREAD

**Issue by sattler** [cmand/yarrp#5]
Hi,

as part of the [IPv6 hitlist service](https://ipv6hitlist.github.io/) we used to run yarrp in parallel with different source addresses. 

Currently we run yarrp-0.5. We saw in the change logs that you added an instance lock in 0.6 [Commit f3c093d](https://github.com/cmand/yarrp/commit/f3c093ddb55b9165db8edfc9091c3feac1a67267). 
What is the reason for this? Is there still a possibility to run multiple instances in parallel for better performance?

**Comment by robertbeverly** [comment]
We had users experiencing problems when they (accidentally) ran multiple instances of yarrp and then got unexpected results.  The intent of the instance locking was to prevent this.  However, yarrp explicitly supports multiple instances (and demultiplexes using an instance field in the probes).  However, the instance locking does not yet support the multi-instance case.  It's a fairly straightforward fix; will get it implemented this week.  Thanks for the feedback.

**Comment by robertbeverly** [comment]
@sattler please let us know if this fixes the issue.  (use the -E argument to specify a unique instance number for each instance).  thanks!

**Comment by sattler** [comment]
@robertbeverly Just tested it with the latest master and it seems to work fine. Thank you very much for the fast fix!
